- hosts: "*"
  become: yes
  tasks:
    - name: Disabling Swap on all nodes
      shell: swapoff -a

    - name: Commenting Swap entries in /etc/fstab
      shell: sed -i '/ swap / s/^/#/' /etc/fstab

    - name: Update repo
      shell: |
        apt update
        apt install -y apt-transport-https curl

    - name: Add Google cloud official GPG key
      shell: |
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
        deb https://apt.kubernetes.io/ kubernetes-xenial main
        EOF
    - name: Update repo
      shell: |
        apt update

    - name: Install kubelet kubeadm kubectl
      shell: |
        apt install -y kubelet=1.21.1-00 kubeadm=1.21.1-00 kubectl=1.21.1-00
        apt-mark hold kubelet kubeadm kubectl
